#!/usr/bin/env python3
"""
Execute trading JSON signals on MetaTrader.

- MT5 mode: connects to an MT5 account through MetaTrader5 Python package
  and sends CREATE/UPDATE/CANCEL/CLOSE requests directly.
- MT4 mode: forwards JSON files to MT4 MQL4 Files/input for EA execution.

This script is compatible with JSON generated by telegram_signal_monitor_mt.py.

Import usage:
    from metatrader_json_executor import book_trade, execute_order, create_mt5_executor
"""

import argparse
import importlib
import json
import os
import shutil
import sys
import re
import configparser
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

def load_dotenv_if_available() -> None:
    """Load .env if python-dotenv is available, otherwise continue silently."""
    try:
        dotenv_module = importlib.import_module("dotenv")
        loader = getattr(dotenv_module, "load_dotenv", None)
        if callable(loader):
            loader()
    except Exception:
        return None


load_dotenv_if_available()


MT5_ORDER_TYPE_MAP = {
    "BUY": "BUY",
    "SELL": "SELL",
    "BUYLIMIT": "BUY_LIMIT",
    "SELLLIMIT": "SELL_LIMIT",
    "BUYSTOP": "BUY_STOP",
    "SELLSTOP": "SELL_STOP",
}


class ExecutorError(Exception):
    """Custom exception for user-facing execution errors."""


def read_config_section(config_file: str) -> Dict[str, str]:
    """Read flat key/value config files or standard INI files."""
    with open(config_file, "r", encoding="utf-8") as handle:
        raw_text = handle.read()

    if re.search(r"^\s*\[", raw_text, re.MULTILINE):
        parser = configparser.ConfigParser(interpolation=None, inline_comment_prefixes=("#", ";"))
        parser.optionxform = str
        parser.read_string(raw_text)
        return dict(parser["DEFAULT"])

    section: Dict[str, str] = {}
    for raw_line in raw_text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        if "=" not in raw_line:
            continue

        key, value = raw_line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value and value[0] not in ("'", '"'):
            value = re.split(r"\s(?=[#;])", value, 1)[0].strip()
        section[key] = value

    return section


def resolve_terminal_paths_from_chat_config(chat_config: str) -> Tuple[str, str, str, str]:
    """Resolve platform and terminal input/output folders using monitor script logic."""
    if not os.path.exists(chat_config):
        raise ExecutorError(f"Chat config file not found: {chat_config}")

    section = read_config_section(chat_config)
    broker = section.get("BROKER", "").strip()
    if not broker:
        raise ExecutorError("BROKER is required in chat config.")

    platform_from_config = (
        section.get("MARKET_TYPE")
        or section.get("MT_TYPE")
        or section.get("PLATFORM")
        or "MT5"
    )
    normalized_platform = str(platform_from_config).strip().upper()
    if normalized_platform in {"MT4", "MQL4", "4"}:
        trading_platform = "mt4"
        mql_folder = "MQL4"
    elif normalized_platform in {"MT5", "MQL5", "5"}:
        trading_platform = "mt5"
        mql_folder = "MQL5"
    else:
        raise ExecutorError(f"Invalid market type '{platform_from_config}'. Use MT4 or MT5.")

    base_terminal_path = os.getenv(
        "MT_BASE_PATH",
        r"C:\\Users\\YourUsername\\AppData\\Roaming\\MetaQuotes\\Terminal",
    )
    terminal_input_folder = f"{base_terminal_path}\\{broker}\\{mql_folder}\\Files\\input"
    terminal_output_folder = f"{base_terminal_path}\\{broker}\\{mql_folder}\\Files\\output"
    return trading_platform, broker, terminal_input_folder, terminal_output_folder


def load_json_file(file_path: Path) -> Dict:
    with file_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def collect_files(single_json: Optional[str], input_dir: Optional[str]) -> List[Path]:
    if single_json:
        path = Path(single_json)
        if not path.exists():
            raise ExecutorError(f"JSON file not found: {path}")
        return [path]

    if not input_dir:
        raise ExecutorError("Provide --json or --input-dir.")

    folder = Path(input_dir)
    if not folder.exists() or not folder.is_dir():
        raise ExecutorError(f"Input directory not found: {folder}")

    files = sorted(folder.glob("*.json"))
    if not files:
        raise ExecutorError(f"No .json files found in: {folder}")
    return files


def normalize_create_type(order_data: Dict) -> Tuple[str, Optional[str]]:
    raw_type = str(order_data.get("type", "")).strip().upper()
    raw_side = str(order_data.get("side", "")).strip().upper()

    if raw_type == "MARKET":
        if raw_side not in {"BUY", "SELL"}:
            raise ExecutorError("For MARKET orders, 'side' must be BUY or SELL.")
        return "MARKET", raw_side

    if raw_type in {"BUY", "SELL"}:
        return "MARKET", raw_type

    mapped = MT5_ORDER_TYPE_MAP.get(raw_type)
    if not mapped:
        raise ExecutorError(f"Unsupported order type: {raw_type}")
    return "PENDING", mapped


def ensure_float(value, field_name: str, required: bool = False) -> Optional[float]:
    if value is None:
        if required:
            raise ExecutorError(f"Missing required field: {field_name}")
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        raise ExecutorError(f"Invalid numeric value for {field_name}: {value}")


def ensure_int(value, field_name: str) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        raise ExecutorError(f"Invalid integer value for {field_name}: {value}")


def forward_to_mt4(file_path: Path, mt4_input_dir: str, archive_dir: Optional[str]) -> str:
    target_dir = Path(mt4_input_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    target_path = target_dir / f"{file_path.stem}_{stamp}.json"
    shutil.copy2(file_path, target_path)

    if archive_dir:
        archive = Path(archive_dir)
        archive.mkdir(parents=True, exist_ok=True)
        shutil.move(str(file_path), str(archive / file_path.name))

    return str(target_path)


def forward_order_data_to_mt4(order_data: Dict, mt4_input_dir: str) -> str:
    """Write order data directly to MT4 input without requiring a source JSON file."""
    target_dir = Path(mt4_input_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    msg_id = str(order_data.get("msg_id") or "json_signal")
    safe_msg_id = re.sub(r"[^A-Za-z0-9._-]", "_", msg_id)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    target_path = target_dir / f"{safe_msg_id}_{stamp}.json"

    with target_path.open("w", encoding="utf-8") as handle:
        json.dump(order_data, handle, indent=2)

    return str(target_path)


class MT5Executor:
    def __init__(
        self,
        login: int,
        password: str,
        server: str,
        terminal_path: Optional[str],
        magic: int,
        deviation: int,
        dry_run: bool,
    ) -> None:
        self.login = login
        self.password = password
        self.server = server
        self.terminal_path = terminal_path
        self.magic = magic
        self.deviation = deviation
        self.dry_run = dry_run
        self.connected = False

        try:
            mt5 = importlib.import_module("MetaTrader5")
        except Exception as exc:
            raise ExecutorError(
                "MetaTrader5 package is not installed. Run: pip install MetaTrader5"
            ) from exc

        self.mt5 = mt5

    def connect(self) -> None:
        kwargs = {"login": self.login, "password": self.password, "server": self.server}
        if self.terminal_path:
            kwargs["path"] = self.terminal_path

        if not self.mt5.initialize(**kwargs):
            raise ExecutorError(f"MT5 initialize failed: {self.mt5.last_error()}")
        self.connected = True

    def shutdown(self) -> None:
        if self.connected:
            self.mt5.shutdown()
            self.connected = False

    def __enter__(self) -> "MT5Executor":
        self.connect()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.shutdown()

    def ensure_symbol(self, symbol: str) -> None:
        info = self.mt5.symbol_info(symbol)
        if info is None:
            raise ExecutorError(f"Symbol not found in MT5 terminal: {symbol}")
        if not info.visible:
            if not self.mt5.symbol_select(symbol, True):
                raise ExecutorError(f"Unable to enable symbol in Market Watch: {symbol}")

    def _order_send(self, request: Dict, context: str) -> Dict:
        if self.dry_run:
            return {"dry_run": True, "context": context, "request": request}

        result = self.mt5.order_send(request)
        if result is None:
            raise ExecutorError(f"{context}: order_send returned None ({self.mt5.last_error()})")

        response = result._asdict()
        retcode = response.get("retcode")
        if retcode != self.mt5.TRADE_RETCODE_DONE:
            raise ExecutorError(f"{context}: failed with retcode {retcode}, response={response}")
        return response

    def create(self, order_data: Dict) -> Dict:
        symbol = str(order_data.get("symbol", "")).strip()
        if not symbol:
            raise ExecutorError("CREATE requires 'symbol'.")
        self.ensure_symbol(symbol)

        volume = ensure_float(order_data.get("volume", 0.1), "volume", required=True)
        sl = ensure_float(order_data.get("sl"), "sl")
        tp = ensure_float(order_data.get("tp"), "tp")
        msg_id = str(order_data.get("msg_id", "json_signal"))

        class_type, mapped_type = normalize_create_type(order_data)

        if class_type == "MARKET":
            tick = self.mt5.symbol_info_tick(symbol)
            if tick is None:
                raise ExecutorError(f"No tick data for symbol: {symbol}")

            order_type = self.mt5.ORDER_TYPE_BUY if mapped_type == "BUY" else self.mt5.ORDER_TYPE_SELL
            price = tick.ask if mapped_type == "BUY" else tick.bid
            request = {
                "action": self.mt5.TRADE_ACTION_DEAL,
                "symbol": symbol,
                "volume": volume,
                "type": order_type,
                "price": price,
                "sl": sl or 0.0,
                "tp": tp or 0.0,
                "deviation": self.deviation,
                "magic": self.magic,
                "comment": f"signal:{msg_id}",
                "type_time": self.mt5.ORDER_TIME_GTC,
                "type_filling": self.mt5.ORDER_FILLING_IOC,
            }
            return self._order_send(request, f"CREATE MARKET {mapped_type} {symbol}")

        price = ensure_float(order_data.get("price"), "price", required=True)
        pending_map = {
            "BUY_LIMIT": self.mt5.ORDER_TYPE_BUY_LIMIT,
            "SELL_LIMIT": self.mt5.ORDER_TYPE_SELL_LIMIT,
            "BUY_STOP": self.mt5.ORDER_TYPE_BUY_STOP,
            "SELL_STOP": self.mt5.ORDER_TYPE_SELL_STOP,
        }
        request = {
            "action": self.mt5.TRADE_ACTION_PENDING,
            "symbol": symbol,
            "volume": volume,
            "type": pending_map[mapped_type],
            "price": price,
            "sl": sl or 0.0,
            "tp": tp or 0.0,
            "deviation": self.deviation,
            "magic": self.magic,
            "comment": f"signal:{msg_id}",
            "type_time": self.mt5.ORDER_TIME_GTC,
            "type_filling": self.mt5.ORDER_FILLING_RETURN,
        }
        return self._order_send(request, f"CREATE {mapped_type} {symbol}")

    def update(self, order_data: Dict) -> Dict:
        ticket = ensure_int(order_data.get("ticket"), "ticket")
        sl = ensure_float(order_data.get("sl"), "sl")
        tp = ensure_float(order_data.get("tp"), "tp")

        positions = self.mt5.positions_get(ticket=ticket)
        if positions:
            position = positions[0]
            request = {
                "action": self.mt5.TRADE_ACTION_SLTP,
                "position": ticket,
                "symbol": position.symbol,
                "sl": sl if sl is not None else position.sl,
                "tp": tp if tp is not None else position.tp,
                "magic": self.magic,
                "comment": f"update:{order_data.get('msg_id', '')}",
            }
            return self._order_send(request, f"UPDATE position {ticket}")

        orders = self.mt5.orders_get(ticket=ticket)
        if orders:
            pending = orders[0]
            price = ensure_float(order_data.get("price", pending.price_open), "price")
            request = {
                "action": self.mt5.TRADE_ACTION_MODIFY,
                "order": ticket,
                "price": price,
                "sl": sl if sl is not None else pending.sl,
                "tp": tp if tp is not None else pending.tp,
                "magic": self.magic,
                "comment": f"update:{order_data.get('msg_id', '')}",
            }
            return self._order_send(request, f"UPDATE pending order {ticket}")

        raise ExecutorError(f"UPDATE: ticket not found as position or pending order: {ticket}")

    def cancel(self, order_data: Dict) -> Dict:
        ticket = ensure_int(order_data.get("ticket"), "ticket")
        request = {
            "action": self.mt5.TRADE_ACTION_REMOVE,
            "order": ticket,
            "magic": self.magic,
            "comment": f"cancel:{order_data.get('msg_id', '')}",
        }
        return self._order_send(request, f"CANCEL order {ticket}")

    def close(self, order_data: Dict) -> Dict:
        ticket = ensure_int(order_data.get("ticket"), "ticket")
        positions = self.mt5.positions_get(ticket=ticket)
        if not positions:
            raise ExecutorError(f"CLOSE: open position not found for ticket {ticket}")

        position = positions[0]
        self.ensure_symbol(position.symbol)
        tick = self.mt5.symbol_info_tick(position.symbol)
        if tick is None:
            raise ExecutorError(f"CLOSE: no tick data for symbol {position.symbol}")

        if position.type == self.mt5.POSITION_TYPE_BUY:
            close_type = self.mt5.ORDER_TYPE_SELL
            price = tick.bid
        else:
            close_type = self.mt5.ORDER_TYPE_BUY
            price = tick.ask

        request = {
            "action": self.mt5.TRADE_ACTION_DEAL,
            "position": ticket,
            "symbol": position.symbol,
            "volume": position.volume,
            "type": close_type,
            "price": price,
            "deviation": self.deviation,
            "magic": self.magic,
            "comment": f"close:{order_data.get('msg_id', '')}",
            "type_time": self.mt5.ORDER_TIME_GTC,
            "type_filling": self.mt5.ORDER_FILLING_IOC,
        }
        return self._order_send(request, f"CLOSE position {ticket}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Execute signal JSON on MT5 directly, or forward to MT4 input folder."
    )
    parser.add_argument("--platform", choices=["mt4", "mt5"])
    parser.add_argument("--chat-config", help="Chat config INI/flat file used to resolve BROKER and MARKET_TYPE")
    parser.add_argument("--json", help="Single JSON file to process")
    parser.add_argument("--input-dir", help="Folder containing JSON files to process")
    parser.add_argument(
        "--archive-dir",
        help="Optional folder where processed source JSON files are moved",
    )

    parser.add_argument("--dry-run", action="store_true", help="Validate and print requests without sending")

    parser.add_argument("--mt4-input-dir", default=os.getenv("MT4_INPUT_FOLDER"), help="MT4 MQL4 Files/input path")

    parser.add_argument("--login", type=int, default=int(os.getenv("MT5_LOGIN", "0")))
    parser.add_argument("--password", default=os.getenv("MT5_PASSWORD", ""))
    parser.add_argument("--server", default=os.getenv("MT5_SERVER", ""))
    parser.add_argument("--terminal-path", default=os.getenv("MT5_TERMINAL_PATH", ""))
    parser.add_argument("--magic", type=int, default=int(os.getenv("MT5_MAGIC", "20260325")))
    parser.add_argument("--deviation", type=int, default=int(os.getenv("MT5_DEVIATION", "20")))

    return parser.parse_args()


def process_order_mt5(executor: MT5Executor, order_data: Dict) -> Dict:
    action = str(order_data.get("action", "")).strip().upper()
    if action == "CREATE":
        return executor.create(order_data)
    if action == "UPDATE":
        return executor.update(order_data)
    if action == "CANCEL":
        return executor.cancel(order_data)
    if action == "CLOSE":
        return executor.close(order_data)
    raise ExecutorError(f"Unsupported action: {action}")


def create_mt5_executor(
    login: Optional[int] = None,
    password: Optional[str] = None,
    server: Optional[str] = None,
    terminal_path: Optional[str] = None,
    magic: Optional[int] = None,
    deviation: Optional[int] = None,
    dry_run: bool = False,
) -> MT5Executor:
    """Build an MT5 executor from explicit args or environment defaults."""
    effective_login = int(login if login is not None else os.getenv("MT5_LOGIN", "0"))
    effective_password = password if password is not None else os.getenv("MT5_PASSWORD", "")
    effective_server = server if server is not None else os.getenv("MT5_SERVER", "")
    effective_terminal_path = terminal_path if terminal_path is not None else os.getenv("MT5_TERMINAL_PATH", "")
    effective_magic = int(magic if magic is not None else os.getenv("MT5_MAGIC", "20260325"))
    effective_deviation = int(deviation if deviation is not None else os.getenv("MT5_DEVIATION", "20"))

    if effective_login <= 0 or not effective_password or not effective_server:
        raise ExecutorError(
            "MT5 execution requires login, password, and server, either as arguments or environment variables."
        )

    return MT5Executor(
        login=effective_login,
        password=effective_password,
        server=effective_server,
        terminal_path=effective_terminal_path or None,
        magic=effective_magic,
        deviation=effective_deviation,
        dry_run=dry_run,
    )


def execute_order(
    order_data: Dict,
    platform: str,
    *,
    mt5_executor: Optional[MT5Executor] = None,
    mt4_input_dir: Optional[str] = None,
    login: Optional[int] = None,
    password: Optional[str] = None,
    server: Optional[str] = None,
    terminal_path: Optional[str] = None,
    magic: Optional[int] = None,
    deviation: Optional[int] = None,
    dry_run: bool = False,
) -> Dict:
    """Execute a single order dict directly, suitable for importing from other scripts."""
    normalized_platform = str(platform).strip().lower()
    if normalized_platform == "mt4":
        if not mt4_input_dir:
            raise ExecutorError("MT4 execution requires mt4_input_dir.")
        out_path = forward_order_data_to_mt4(order_data, mt4_input_dir)
        return {"platform": "mt4", "forwarded_to": out_path, "order_data": order_data}

    if normalized_platform != "mt5":
        raise ExecutorError(f"Unsupported platform: {platform}")

    if mt5_executor is not None:
        return process_order_mt5(mt5_executor, order_data)

    with create_mt5_executor(
        login=login,
        password=password,
        server=server,
        terminal_path=terminal_path,
        magic=magic,
        deviation=deviation,
        dry_run=dry_run,
    ) as executor:
        return process_order_mt5(executor, order_data)


def book_trade(
    *,
    symbol: str,
    side: str,
    volume: float,
    platform: str = "mt5",
    order_type: str = "MARKET",
    price: Optional[float] = None,
    sl: Optional[float] = None,
    tp: Optional[float] = None,
    broker: Optional[str] = None,
    msg_id: Optional[str] = None,
    mt5_executor: Optional[MT5Executor] = None,
    mt4_input_dir: Optional[str] = None,
    login: Optional[int] = None,
    password: Optional[str] = None,
    server: Optional[str] = None,
    terminal_path: Optional[str] = None,
    magic: Optional[int] = None,
    deviation: Optional[int] = None,
    dry_run: bool = False,
) -> Dict:
    """High-level importable helper to place a trade directly from Python code."""
    order_data = {
        "action": "CREATE",
        "symbol": symbol,
        "side": side,
        "type": order_type,
        "volume": volume,
        "price": price if price is not None else 0.0,
        "sl": sl if sl is not None else 0.0,
        "tp": tp if tp is not None else 0.0,
        "msg_id": msg_id or datetime.now().strftime("direct_%Y%m%d_%H%M%S_%f"),
    }
    if broker:
        order_data["broker"] = broker

    return execute_order(
        order_data,
        platform,
        mt5_executor=mt5_executor,
        mt4_input_dir=mt4_input_dir,
        login=login,
        password=password,
        server=server,
        terminal_path=terminal_path,
        magic=magic,
        deviation=deviation,
        dry_run=dry_run,
    )


def execute_orders(
    orders: List[Dict],
    platform: str,
    *,
    mt5_executor: Optional[MT5Executor] = None,
    mt4_input_dir: Optional[str] = None,
    login: Optional[int] = None,
    password: Optional[str] = None,
    server: Optional[str] = None,
    terminal_path: Optional[str] = None,
    magic: Optional[int] = None,
    deviation: Optional[int] = None,
    dry_run: bool = False,
) -> List[Dict]:
    """Execute multiple orders directly from Python code."""
    normalized_platform = str(platform).strip().lower()
    if normalized_platform == "mt4":
        return [
            execute_order(order, normalized_platform, mt4_input_dir=mt4_input_dir, dry_run=dry_run)
            for order in orders
        ]

    if normalized_platform != "mt5":
        raise ExecutorError(f"Unsupported platform: {platform}")

    if mt5_executor is not None:
        return [process_order_mt5(mt5_executor, order) for order in orders]

    with create_mt5_executor(
        login=login,
        password=password,
        server=server,
        terminal_path=terminal_path,
        magic=magic,
        deviation=deviation,
        dry_run=dry_run,
    ) as executor:
        return [process_order_mt5(executor, order) for order in orders]


def main() -> int:
    args = parse_args()

    effective_platform = args.platform
    effective_input_dir = args.input_dir
    effective_mt4_input_dir = args.mt4_input_dir

    if args.chat_config:
        try:
            cfg_platform, cfg_broker, cfg_input, _cfg_output = resolve_terminal_paths_from_chat_config(
                args.chat_config
            )
            if effective_platform and effective_platform != cfg_platform:
                raise ExecutorError(
                    f"Platform mismatch: --platform={effective_platform} but config MARKET_TYPE={cfg_platform.upper()}"
                )

            effective_platform = effective_platform or cfg_platform
            if cfg_platform == "mt5":
                effective_input_dir = effective_input_dir or cfg_input
            if cfg_platform == "mt4":
                effective_mt4_input_dir = effective_mt4_input_dir or cfg_input

            print(f"[INFO] Resolved broker from config: {cfg_broker}")
            print(f"[INFO] Resolved platform from config: {cfg_platform}")
            print(f"[INFO] Resolved terminal input folder: {cfg_input}")
        except ExecutorError as exc:
            print(f"[ERROR] {exc}")
            return 1

    if not effective_platform:
        print("[ERROR] Provide --platform or --chat-config with MARKET_TYPE.")
        return 1

    try:
        files = collect_files(args.json, effective_input_dir)
    except ExecutorError as exc:
        print(f"[ERROR] {exc}")
        return 1

    if effective_platform == "mt4":
        if not effective_mt4_input_dir:
            print("[ERROR] MT4 mode requires --mt4-input-dir or MT4_INPUT_FOLDER env var")
            return 1

        ok = 0
        fail = 0
        for file_path in files:
            try:
                _ = load_json_file(file_path)
                out_path = forward_to_mt4(file_path, effective_mt4_input_dir, args.archive_dir)
                print(f"[OK] Forwarded to MT4 input: {out_path}")
                ok += 1
            except Exception as exc:
                print(f"[ERROR] {file_path}: {exc}")
                fail += 1

        print(f"[SUMMARY] mt4 forwarded={ok} failed={fail}")
        return 0 if fail == 0 else 2

    if args.login <= 0 or not args.password or not args.server:
        print("[ERROR] MT5 mode requires --login, --password, --server (or env vars MT5_LOGIN/MT5_PASSWORD/MT5_SERVER)")
        return 1

    try:
        executor = MT5Executor(
            login=args.login,
            password=args.password,
            server=args.server,
            terminal_path=args.terminal_path or None,
            magic=args.magic,
            deviation=args.deviation,
            dry_run=args.dry_run,
        )
        executor.connect()
    except ExecutorError as exc:
        print(f"[ERROR] {exc}")
        return 1

    ok = 0
    fail = 0

    try:
        for file_path in files:
            try:
                order_data = load_json_file(file_path)
                result = process_order_mt5(executor, order_data)
                print(f"[OK] {file_path.name}: {result}")

                if args.archive_dir:
                    archive = Path(args.archive_dir)
                    archive.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(file_path), str(archive / file_path.name))

                ok += 1
            except Exception as exc:
                print(f"[ERROR] {file_path}: {exc}")
                fail += 1
    finally:
        executor.shutdown()

    print(f"[SUMMARY] mt5 executed={ok} failed={fail}")
    return 0 if fail == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
